In [2]:
import pandas as pd
import numpy as np
import scipy.stats as sts

In [13]:
xyz = pd.io.stata.read_stata('xyz.dta')
xyz.to_csv('xyz.csv')

anscombe = pd.io.stata.read_stata('anscombe.dta')
anscombe.to_csv('anscombe.csv')

# bwages = pd.io.stata.read_stata('bwages.dta')
# bwages.to_csv('bwages.csv')

In [9]:
xyz

            x          y         z
0    9.265379   8.272652 -1.297930
1   12.474401  11.537406  1.832294
2    9.931052  10.417721 -0.684030
3   12.485246   7.536047  1.939716
4    9.785354  14.575685 -0.930084
5    9.228371   7.485125 -1.315930
6   10.199236  12.322157 -0.461811
7    8.606638  12.142447 -2.050072
8    8.308434  13.404581 -2.378738
9   13.485441   6.958958  2.953840
10   7.085776  11.171252 -3.547493
11   9.446997   6.359108 -1.070127
12   8.469862   7.024108 -2.063312
13   8.653094   4.455360 -1.818081
14  12.170412   8.971422  1.590238
15  13.366251   9.075768  2.783558
16   9.986305   7.852328 -0.566859
17  12.982099   5.586565  2.483621
18  15.065186  11.661961  4.420073
19  10.082019  10.605659 -0.537599
20  12.240947   8.444518  1.673490
21   9.911062  10.330864 -0.701923
22   9.147456  10.709967 -1.474679
23   9.316863   8.619178 -1.254809
24  10.035723  11.254993 -0.599568
25  12.839991  11.677240  2.194509
26   8.108401   5.338270 -2.384084
27   7.560929  11.090576 -3.070393
28  13.821456  11.741128  3.174432
29   9.423120   7.721225 -1.126879
30  10.490652  11.383843 -0.147748
31   6.701103   8.145541 -3.859138
32   9.883237   5.031465 -0.601843
33   9.484987  10.554626 -1.133399
34  15.078704   6.498067  4.558226
35  11.021663  10.256865  0.410463
36  12.094258   7.330524  1.553689
37  10.051643   8.920321 -0.527297
38  13.394247  12.767269  2.722457
39  11.925886  10.317522  1.313223

In [10]:
anscombe

    x1     y1  x2    y2  x3     y3  x4     y4
0   10   8.04  10  9.14  10   7.46   8   6.58
1    8   6.95   8  8.14   8   6.77   8   5.76
2   13   7.58  13  8.74  13  12.74   8   7.71
3    9   8.81   9  8.77   9   7.11   8   8.84
4   11   8.33  11  9.26  11   7.81   8   8.47
5   14   9.96  14  8.10  14   8.84   8   7.04
6    6   7.24   6  6.13   6   6.08   8   5.25
7    4   4.26   4  3.10   4   5.39  19  12.50
8   12  10.84  12  9.13  12   8.15   8   5.56
9    7   4.82   7  7.26   7   6.42   8   7.91
10   5   5.68   5  4.74   5   5.73   8   6.89

In [14]:
slope, intercept, r_value, p_value, std_err = sts.linregress(anscombe['x1'], anscombe['x2'])

In [15]:
r_value**2

1.0

In [16]:
p_value

5.8534851285390365e-90